services:
  mainpage:
    image: ghcr.io/josestud/mainpage:597719926481184598695eaa51ea43435416313a
    container_name: mainpage
    restart: unless-stopped
    pull_policy: always
    environment:
      - MULTI_SCROBBLER_BASE_URL=http://multi-scrobbler:9078
    ports:
      - "8000:80"
    depends_on:
      - multi-scrobbler

  multi-scrobbler:
    image: ghcr.io/josestud/mainpage:597719926481184598695eaa51ea43435416313a
    container_name: multi-scrobbler
    restart: unless-stopped
    ports:
      - "9078:9078"
    volumes:
      - multi_scrobbler_config:/config

volumes:
  multi_scrobbler_config:
